### ISSUE TITLE
Getting error Undefined is not an object (evaluating 'this._drawer.open()').

### ISSUE THREAD

**Issue by charlie-rc** [caroaguilar/NavigationDrawerExample#1]
Hello,

I am trying to open the drawer from menu button within toolbar , but it fails to open giving  error: "undefined is not an object (evaluating 'this._drawer.open()')".

Any help will be appreciated?

**Comment by caroaguilar** [comment]
Hi! 

Are you using the code same as it is here?

Btw, I just updated the project to use latest React, React-Native and the rest npm packages.

**Comment by caroaguilar** [comment]
Just tested the code and it's working. Maybe it's a context error so `this` refers to a different context. Can you show me your code please?

**Comment by charlie-rc** [comment]
Yes i am using the exactly the same code you have updated on github, still it is giving me error. I am using react native 0.27.0, node 6.2.2 and npm 1.4.9.

**Comment by caroaguilar** [comment]
Please pull the latest. I made some changes, working now in both Android and iOS. I also decided to make a big change to use the same `Navigator` component for both platforms and stopped using `NavigatorIOS`, so the code is a bit different.

To avoid scope issues, I decided to use events for the menu buttons actions. There is an example for menu and back button.

There are some styles issues in Android that I'll fix in a few, but at least now it's functional and working with no errors.

Try it and let me know if it gives you problems :)

**Comment by caroaguilar** [comment]
Also I added  [React-Native-Vector-Icons](https://github.com/oblador/react-native-vector-icons) for the menu icons so please after pulling the latest install `npm install rnpm -g` and then run `rnpm link react-native-vector-icons`. More info in the README

**Comment by charlie-rc** [comment]
Hello,
When i updated npm and node it started working..thanks for your suggestions...
But now i am facing another issue , the taptoclose property is not working on android devices(I m trying on nexus and hp tabs)...
Any help will be appreciated...
Thanks in advance....

**Comment by caroaguilar** [comment]
tapToClose is working for me in my Nexus 5, however I can't help you there because that component is not mine, this is the component [React-Native-Drawer](https://github.com/root-two/react-native-drawer) so you might want to create an issue in that project and they could help you more.

Thanks!
